title: "요일별 주간 극단값 집중 현상 재해석"
description: "금융시장의 주간 극단값 패턴에 대한 실증 연구"
author: "김현우"
email: "hwkim3330@gmail.com"

theme: jekyll-theme-cayman
markdown: kramdown

kramdown:
  input: GFM
  hard_wrap: false
  math_engine: mathjax
  syntax_highlighter: rouge

plugins:
  - jekyll-seo-tag
  - jekyll-sitemap

baseurl: ""
url: "https://hwkim3330.github.io/stockpaper"

lang: ko-KR
timezone: Asia/Seoul

navigation:
  - title: Home
    url: /
  - title: Paper
    url: /paper
  - title: About
    url: /about

google_analytics:
show_downloads: false
